version: '3.7'

services:

  sample:
    container_name: front_container
    build:
      context: front/.
      dockerfile: front/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true