version: '3.7'

services:

  sample:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/front'
      - '/front/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true